Targets:
  PXBoardQ: #All options enabled
    Name: PXBoardQ
    TargetImage: assets/images/PXBoardQ-latest.img
    SkipUpdate: False
    Assets:
      BaseImage:
        path: assets/images/PXBoardQ-latest.img
        url : https://pxlinux.s3.us-west-1.amazonaws.com/LATEST/PXBoardQ-latest.img.zip
      RootFS:
        path: assets/rootfs #Directory structure in this path is preserved from '/'. Destination can't be symlink.
      Packages:
        path: assets/packages #All .pkg.tar.xz files and packages listed in pacman_packages.txt will be installed.
      Scripts:
        path: assets/update-scripts


BuildCommand:
  cmd: helper_scripts/build_img.sh
  params:
    - BaseImage
    - TargetImage
    - U-Boot
    - RootFS
    - Packages
    - Scripts
